##===- projects/durandal/tools/clips/Makefile ---------------*- Makefile -*-===##

#
# Indicate where we are relative to the top of the source tree.
#
DURANDAL_LEVEL=../..

#
# Give the name of the tool.
#
TOOLNAME=kc

#
# List libraries that we'll need
# We use LIBS because sample is a dynamic library.
#
USEDLIBS = ExpertSystem.a clips.a rampancy.a
LINK_COMPONENTS = all
#
# Include Makefile.common so we know what to do.
#
include $(DURANDAL_LEVEL)/Makefile

