##===- projects/sample/lib/sample/Makefile -----------------*- Makefile -*-===##

#
# Indicate where we are relative to the top of the source tree.
#
DURANDAL_LEVEL=../..

#
# Give the name of a library.  This will build a dynamic version.
#
LIBRARYNAME=electron

#
# Include Makefile.common so we know what to do.
#
include $(DURANDAL_LEVEL)/Makefile
