##===- projects/durandal/lib/Makefile ------------------------*- Makefile -*-===##
# Modified by Joshua Scoggins to work with durandal
#
# Relative path to the top of the source tree.
#
DURANDAL_LEVEL=..

#
# List all of the subdirectories that we will compile.
#
DIRS=clips ExpertSystem rampancy indirect core pipeline passes

include $(DURANDAL_LEVEL)/Makefile
