##===- projects/durandal/lib/Makefile ------------------------*- Makefile -*-===##
# Modified by Joshua Scoggins to work with durandal
#
# Relative path to the top of the source tree.
#
LEVEL=..

#
# List all of the subdirectories that we will compile.
#
DIRS=clips LibExpertSystem

include $(LEVEL)/Makefile.common
