##===- projects/durandal/tools/Makefile ----------------------*- Makefile -*-===##

#
# Relative path to the top of the source tree.
#
DURANDAL_LEVEL=..

#
# List all of the subdirectories that we will compile.
#
DIRS=durandal kclang kbc

include $(DURANDAL_LEVEL)/Makefile
